### ISSUE TITLE
About the Contrastive Loss

### ISSUE THREAD

**Issue by lixiangyu-1008** [TengdaHan/DPC#12]
Hi @TengdaHan,    
Thanks for great work,

I haven't found the NCE Loss in your source code, Could you please show me where the implement of NCE Loss :)

**Comment by WeidiXie** [comment]
Check https://github.com/TengdaHan/DPC/blob/ac25b1b8fe86bb5e2c5547cd4bc33a8b8f2a5424/dpc/main.py#L67

https://github.com/TengdaHan/DPC/blob/ac25b1b8fe86bb5e2c5547cd4bc33a8b8f2a5424/dpc/main.py#L216

**Comment by lixiangyu-1008** [comment]
Thanks for your reply,
This is a CorssEntropy Loss, where the implement of dot-production as you described in Eq.(5) in paper?

**Comment by WeidiXie** [comment]
That's exactly the InfoNCE loss.

**Comment by TengdaHan** [comment]
Some explanation: 
`score_flattened` is a square matrix having the dot product of all Pred-GT pairs, including one positive pair in each row; 
`target_flattened` is the index of positive pairs, the diagnal in this case. 
`CrossEntropyLoss` is the negative `LogSoftmax` of the targeted class, which is exactly NCE loss.

Simple and beautiful, isn't it.

**Comment by lixiangyu-1008** [comment]
@WeidiXie @TengdaHan 
Thanks for your prompt reply !
I think I have understand it !!
