### ISSUE TITLE
Context and hidden state

### ISSUE THREAD

**Issue by ruoshiliu** [TengdaHan/DPC#16]
Hi, I'm a little confused regarding the notation in your paper and your code and hope you could provide some clarification. In your paper, the aggregation function has two outputs, one is c_t, and the other one is the hidden state. In this part of your code (in DPC/model_3d.py):
```
pred = []
for i in range(self.pred_step):
      # sequentially pred future
      p_tmp = self.network_pred(hidden)
      pred.append(p_tmp)
       _, hidden = self.agg(self.relu(p_tmp).unsqueeze(1), hidden.unsqueeze(0))
      hidden = hidden[:,-1,:]
pred = torch.stack(pred, 1) # B, pred_step, xxx
del hidden
```
where the variable `hidden` is fed into function phi(.). Then `hidden` and `phi(hidden)` are fed into the aggregation function. Does it mean c_t is just the hidden state? What might be the 'context representation' mentioned in the paper in that case?

**Comment by TengdaHan** [comment]
Hi, you are right, what we meant `c_t` in the paper is just the hidden state of GRU. 
Precisely, in paper Fig 2, two horizontal arrows before `x_{t+1}` and `x_{t+2}` are not necessary.

**Comment by ruoshiliu** [comment]
Thanks for the prompt answer! That clarifies a lot of confusion. Just one quick follow-up question: as I understand it, the `context` in model_3d_lc.py is the concatenated hidden states of each time step correct?
```
feature = F.avg_pool3d(feature, (self.last_duration, 1, 1), stride=1)
feature = feature.view(B, N, self.param['feature_size'], self.last_size, self.last_size) # [B*N,D,last_size,last_size]
context, _ = self.agg(feature)
context = context[:,-1,:].unsqueeze(1)
context = F.avg_pool3d(context, (1, self.last_size, self.last_size), stride=1).squeeze(-1).squeeze(-1)
```
But since `context = context[:,-1,:].unsqueeze(1)` which is effectively the same as `hidden` correct? Is it the same as projecting the last `hidden` state to the action space?

**Comment by TengdaHan** [comment]
Yes, you're right. They refer to the same thing, just different names between pre-training and evaluation codes.
