### ISSUE TITLE
gray scale performance

### ISSUE THREAD

**Issue by YuqiHUO** [TengdaHan/DPC#19]
Hi, I find that you actually don't perform grayscale, but the channel split in .augmentation.py

Do you know the performances between these two kinds of augmentation methods? Thanks!

**Comment by TengdaHan** [comment]
For implementation efficiency, we use channel splitting. Grayscale is just a linear combination of there channels and I don't think they have a big difference in the representation performance.
I haven't compared the difference between the two.
