### ISSUE TITLE
Dimensions [B, N, C, SL, W, H] of input block?

### ISSUE THREAD

**Issue by sarimmehdi** [TengdaHan/DPC#2]
Hello. I don't understand what the letter SL stands for in the above? Is it **stride length**? And do B, N, and C stand for **batch**, **sequence** **number**, and **channel**?

**Comment by TengdaHan** [comment]
Haha. It means `[Batch, Numer of sequence, Channel, Sequence Length, Width, Height]`.
e.g. if batch size is 16, if for each video we take 8 video blocks with each video block contains 5 frames, (that is 40 frames for one video, but cut into 8 chunks, one of the settings we use in the paper), image size is 128x128, then the input block is `[16, 8, 3, 5, 128, 128]`.

**Comment by sarimmehdi** [comment]
Thank you!
