### ISSUE TITLE
Pre-training on UCF101

### ISSUE THREAD

**Issue by Yuliang-Zou** [TengdaHan/DPC#20]
Hi, I wonder if you can provide the model checkpoints for pre-training on UCF-101, and the pre-train hyperparameters/instruction of it.

Thank you so much!

**Comment by TengdaHan** [comment]
Hi! Check here for the pre-trained model: [3D-ResNet18-UCF101-128x128](http://www.robots.ox.ac.uk/~htd/dpc/ucf101-rgb-128_resnet18_dpc.pth.tar). Let me know if you cannot load it properly. 

My hyperparameter setting is identical to the command provided for K400 pre-train, but I reduce lr by 1/10 at epoch 300 and 400, totally trained for 500 epochs. Actually, the pre-training is not sensitive to this schedule. Others have re-produced even better results than our paper submission (https://github.com/TengdaHan/DPC#dpc-results). Hope it works well on your side.
