### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by praveenr2998** [TengdaHan/DPC#23]
How much time did it take to train the initial self supervised model using UCF101 and fine tuning again with UCF101 using 124*124 resolution? 
I am having a plan to train it but availability of GPU for the required time is a constraint.

**Comment by TengdaHan** [comment]
e.g. if using 2 Nvidia P40 GPUs, under 128x128 resolution, pretraining on UCF101 would take less than 1 day, finetuning again takes less than 1 day. I would estimate totally takes about 2 days.

Better or more GPUs can accelerate, for sure.

**Comment by praveenr2998** [comment]
Thank you so much.
