### ISSUE TITLE
Link to pretrained model on UCF101 not working

### ISSUE THREAD

**Issue by sergiuoprea** [TengdaHan/DPC#24]
Hi there,

It would be nice to fix the link (http://www.robots.ox.ac.uk/~htd/dpc/ucf101-rgb-128_resnet18_dpc.pth.tar) to the pretrained model on UCF101. 

Thanks in advance and keep up the good work!

**Comment by TengdaHan** [comment]
Thank you for letting me know. 
I don't know why, but it works now. Try copy-paste in new browser window or use wget.

**Comment by sergiuoprea** [comment]
Done. The copy-paste of the link in the browser works! Clicking on the 3D-ResNet18-UCF101-128x128 link in the Readme.md is not working using Google Chrome. However, it works in Microsoft Edge. Strange, but problem solved! Thanks for the prompt answer.
