### ISSUE TITLE
Allow compatibility with latest torch (torch 18.1)

### ISSUE THREAD

**Issue by colleenjg** [TengdaHan/DPC#25]
I've been running the codebase with one of the latest torch versions (18.1) with only 3 small compatibility problems coming up, per my usage. 

`dpc/main.py`, lines 215 and 267:
- `target_flattened` raises 2 errors:
    - It is not automatically placed on `cuda` when created, which leads to an error when `criterion()` is called. 
      **=> Solution: explicitly place on cuda before the call to `criterion()`**
    - It is a `boolean` tensor, and `argmax()` now raises an error with boolean tensors. 
      **=> Solution: convert to `int` before calling `argmax()`.**

`utils/utils.py`, line 53:
- `.view(-1)` in `correct_k = correct[:k].view(-1).float().sum(0)` raises a runtime error (message: view size is not compatible with input tensor's size and stride...) 
  **=> Solution: either use `.reshape(-1)` or make a call to `.contiguous()` before using `.view(-1)`.**

The bugs are quite minor with easy solutions that shouldn't cause a problem for previous torch versions. I am happy to make a pull request if helpful!

Thanks! :)

**Comment by TengdaHan** [comment]
Ahh, thank you for the checking and I am very grateful if you can make a pull request!

**Comment by colleenjg** [comment]
Great! Just made the above pull request.
