### ISSUE TITLE
pretrained weight files aren't able to decompress

### ISSUE THREAD

**Issue by andreiamatuni** [TengdaHan/DPC#27]
I've tried to decompress the pretrained weights files using a few different methods - built-in macOS decompressor in Finder, terminal based tar utility, as well as the Unarchiver app on macOS. I've also tried using the CLI tar utility on Google Colab where I keep running into a similar error:

macOS tar CLI:  ```tar: Error opening archive: Unrecognized archive format```
On Google Colab CLI: tar: ```This does not look like a tar archive```

I'm trying to use the UCF101 dataset and weights. Are these weights compressed using a special method? I'd appreciate any and all help with this.

**Comment by TengdaHan** [comment]
Just do `weights = torch.load('filename.pth.tar', map_location='cpu')`

**Comment by andreiamatuni** [comment]
looks like that works, thank you!
