### ISSUE TITLE
What do you mean by sequential prediction in your paper?

### ISSUE THREAD

**Issue by sarimmehdi** [TengdaHan/DPC#4]
Hello. I read in your paper that you did an ablation study where you removed the sequential prediction and replaced it with parallel prediction where you predicted all three time steps with a different fully connected layer. I understand parallel prediction but I don't understand what you really mean by sequential prediction.

By sequential prediction do you mean that at every time step you use the same fully connected layer to do the prediction or that you use one fully connected layer at the final time step only?

**Comment by WeidiXie** [comment]
Hi, 

I'll use the Figure 2 in the paper to explain this.

As you mentioned, parallel prediction means to predict z&#770;<sub>t+1,</sub> z&#770;<sub>t+2,</sub> ..., with separate FC layers.

While for sequential prediction, it's simply meaning an autoregressive model, so we use the convGRU. In detail, the context vector c<sub>t</sub> computed from z<sub>t</sub> and hidden states from previous step (not shown in the figure), is used to predict the z&#770;<sub>t+1</sub>.

Then the predicted z&#770;<sub>t+1,</sub> and hidden states are further applied to compute c<sub>t+1,</sub>. Ideally, now  c<sub>t+1,</sub> will include all the information from t+1 step, and it can be used to predict z&#770;<sub>t+2,</sub>
