### ISSUE TITLE
Why are you shuffling the sequence of images?

### ISSUE THREAD

**Issue by sarimmehdi** [TengdaHan/DPC#8]
I saw in your code that you shuffle your images around [(main.py).](https://github.com/TengdaHan/DPC/blob/7bb73f4a934bbf34eda10a6102629bacb9b4e348/dpc/main.py#L303) Don't you want to preserve the sequence?

**Comment by TengdaHan** [comment]
Hi, this RandomSampler is to randomly form batches from the entire video dataset (e.g. randomly form batch size 64 from 300,000 videos), not shuffle frames. Frames are definitely not shuffled.

**Comment by sarimmehdi** [comment]
Thank you very much, I forgot that you were using videos and not frames that were already provided before-hand. This clears up a lot, actually, my model seems to be performing much better now (before, the order of all the frames was random lol)
